// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFvj-8208trOW07JdUXBhahAyKq3Nyr-A',
    appId: '1:698581022691:web:ea0163d1d307620e1d12d6',
    messagingSenderId: '698581022691',
    projectId: 'diagramproject-f4e78',
    authDomain: 'diagramproject-f4e78.firebaseapp.com',
    storageBucket: 'diagramproject-f4e78.appspot.com',
    measurementId: 'G-CDX8K15MTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFimSctYQmt_ZrpjiNJE7fYWRfL0sF5CM',
    appId: '1:698581022691:android:c026da6e30c290bf1d12d6',
    messagingSenderId: '698581022691',
    projectId: 'diagramproject-f4e78',
    storageBucket: 'diagramproject-f4e78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnrx5J__dksKAfiERJFHBr_uerxkHCGT8',
    appId: '1:698581022691:ios:7ca193e5fa16e1751d12d6',
    messagingSenderId: '698581022691',
    projectId: 'diagramproject-f4e78',
    storageBucket: 'diagramproject-f4e78.appspot.com',
    iosClientId: '698581022691-qlbf2kvr16g4jj5ml5b2t8tr0l0gveb0.apps.googleusercontent.com',
    iosBundleId: 'com.example.secondFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnrx5J__dksKAfiERJFHBr_uerxkHCGT8',
    appId: '1:698581022691:ios:7ca193e5fa16e1751d12d6',
    messagingSenderId: '698581022691',
    projectId: 'diagramproject-f4e78',
    storageBucket: 'diagramproject-f4e78.appspot.com',
    iosClientId: '698581022691-qlbf2kvr16g4jj5ml5b2t8tr0l0gveb0.apps.googleusercontent.com',
    iosBundleId: 'com.example.secondFlutterApp',
  );
}
